# Generated by Django 4.2.11 on 2024-08-08 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fts_app", "0011_alter_message_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="Noting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("noting_no", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("filename_doc", models.CharField(max_length=255)),
                ("filename_dak_doc", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.PositiveSmallIntegerField(default=1)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fts_app.role"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fts_app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotingUserMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.IntegerField(default=1)),
                ("is_opened", models.IntegerField(default=0)),
                ("is_forwarded", models.IntegerField(default=0)),
                ("message", models.TextField(null=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_noting",
                        to="fts_app.user",
                    ),
                ),
                (
                    "noting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="noting_mappings",
                        to="fts_app.noting",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_noting",
                        to="fts_app.user",
                    ),
                ),
            ],
        ),
    ]
