# Generated by Django 4.2.11 on 2024-08-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fts_app", "0012_noting_notingusermap"),
    ]

    operations = [
        migrations.AddField(
            model_name="noting",
            name="comment",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="noting",
            name="digital_signature",
            field=models.TextField(null=True),
        ),
    ]
