# Generated by Django 4.2.11 on 2024-08-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fts_app", "0014_noting_selected_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notingusermap",
            name="digital_signature",
            field=models.TextField(null=True),
        ),
    ]
